# Generated by Django 4.0.4 on 2022-07-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('user_name', models.CharField(max_length=25)),
                ('profile_pic', models.FileField(upload_to='')),
                ('address', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'register_doctor',
            },
        ),
        migrations.CreateModel(
            name='resiter_patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('user_name', models.CharField(max_length=25)),
                ('profile_pic', models.FileField(upload_to='')),
                ('address', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'register_patient',
            },
        ),
    ]
