# Generated by Django 4.0.4 on 2022-07-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_resiter_patient_register_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_doctor',
            name='profile_pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
