# Generated by Django 4.0.4 on 2022-07-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_register_doctor_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_doctor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='register_patient',
            name='address',
        ),
        migrations.AddField(
            model_name='register_doctor',
            name='address_line1',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='register_doctor',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='register_doctor',
            name='password2',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='register_doctor',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='register_doctor',
            name='state',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='register_patient',
            name='address_line1',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='register_patient',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='register_patient',
            name='password2',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='register_patient',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='register_patient',
            name='state',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='register_doctor',
            name='email',
            field=models.EmailField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='register_doctor',
            name='first_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='register_doctor',
            name='last_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='register_doctor',
            name='password',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='register_doctor',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='register_doctor',
            name='user_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='register_patient',
            name='email',
            field=models.EmailField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='register_patient',
            name='first_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='register_patient',
            name='last_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='register_patient',
            name='password',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='register_patient',
            name='user_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
