# Generated by Django 4.0.4 on 2022-07-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_remove_register_doctor_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, max_length=10, null=True)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('user_name', models.CharField(max_length=25, null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='images/')),
                ('address_line1', models.CharField(max_length=75, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.CharField(max_length=25, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=25, null=True)),
                ('password', models.CharField(max_length=25, null=True)),
                ('password2', models.CharField(max_length=25, null=True)),
            ],
            options={
                'db_table': 'register',
            },
        ),
        migrations.DeleteModel(
            name='register_doctor',
        ),
        migrations.DeleteModel(
            name='register_patient',
        ),
    ]
