# Generated by Django 4.0.4 on 2022-07-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_rename_register_register_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_doctor',
            name='user_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
