# Generated by Django 4.0.4 on 2022-07-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_alter_register_doctor_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_doctor',
            name='user_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
