# Generated by Django 4.0.4 on 2022-07-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_alter_register_doctor_user_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register_doctor',
            table='register',
        ),
    ]
