# Generated by Django 4.0.4 on 2022-07-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_alter_register_doctor_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register_doctor',
            table='register_doctor',
        ),
    ]
