# Generated by Django 4.0.4 on 2022-07-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_alter_register_doctor_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_doctor',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'doctor'), ('patient', 'patient')], max_length=128),
        ),
    ]
