# Generated by Django 4.0.4 on 2022-07-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_alter_register_doctor_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25, null=True)),
                ('title', models.CharField(max_length=25, null=True)),
                ('image', models.FileField(upload_to='blogimages/')),
                ('category', models.CharField(choices=[('Mental health', 'Mental health'), ('covid19', 'covid19'), ('heart disease', 'heart disease'), ('immunization', 'immunization')], max_length=25)),
                ('summary', models.CharField(max_length=360, null=True)),
                ('content', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
