# Generated by Django 4.0.4 on 2022-07-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='draft',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.FileField(null=True, upload_to='blogimages/'),
        ),
    ]
