# Generated by Django 4.0.4 on 2022-07-29 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_appointments_alter_blogs_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='appointment_time',
            new_name='appointment_endtime',
        ),
        migrations.AddField(
            model_name='appointments',
            name='appointment_starttime',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
